/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sy_android_test_jni_HelloJni */

#ifndef _Included_sy_android_test_jni_HelloJni
#define _Included_sy_android_test_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sy_android_test_jni_HelloJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sy_android_test_jni_HelloJni_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
